#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ACCEL,          sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_Matrix_S1_1, motorD,        tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, PIDControl, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

// Declare the x, y, and z values
int x = 0,
	  y = 0,
	  z = 0;


/**
 * Set the x, y and z values
 */
void getValues(){
	getAccel(ACCEL, x, y, z);

	// Normalize the values of the Accel sensor
	if (x > 405) x -= 1024;
	if (y > 405) y -= 1024;
	if (z > 405) z -= 1024;
}


/**
 * Execute this function when the robot is on the ramp
 */
void isOnRamp(){
	playImmediateTone(1200, 20);
	wait1Msec(200);


// Drive forward
	motor[motorD] = 20;
	motor[motorF] = 20;

	getValues();
	while(x < 50){
		getValues();
		wait1Msec(10);
	}
	/* x > - 60, so on flat ground */



	// And disable them
	motor[motorD] = 0;
	motor[motorF] = 0;

	playImmediateTone(1200, 20);
	wait1Msec(200);
}

/**
 * Execute this function when the robot is on the ground
 */
void isOnGround(){

	playImmediateTone(400, 20);
	wait1Msec(200);


	motor[motorD] = 100;
	motor[motorF] = 100;
	wait1Msec(1000);
}

task main(){
	bool onramp = false;
	// Wait 0.1 seconds to give some time to initialize the values
	wait1Msec(100);
	getValues();
	// Turn on the engines...
	motor[motorD] = 20;
	motor[motorF] = 20;

	// ...wait 2 seconds...
	//wait1Msec(2000);

	for (int g = 0; g<200; g++)
	{
		// 2 sec
		wait1Msec(10);
		getValues();

		if(x < -60){
			onramp = true;
			g = 2001;
		}

	}
	// ...and disable the engines.
	// Get the x, y, and z values
		motor[motorD] = 0;
	motor[motorF] = 0;
	getValues();
	// The robot is on the ramp
		// So execute the isOnRamp function
		if(onramp) {  isOnRamp(); }

		// The robot is on the floor
		// So execute the isOnGround function
		else {isOnGround(); }

}
