#pragma config(Sensor, S4,     ACCEL,          sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

int x = 0,
	  y = 0,
	  z = 0;

void getValues(){
	getAccel(ACCEL, x, y, z);

	// Normalize the values of the Accel sensor
	if (x > 405) x -= 1024;
	if (y > 405) y -= 1024;
	if (z > 405) z -= 1024;
}	  

task main(){
	
	wait1Msec(100);

	getAccel(ACCEL, x, y, z);

	// Normalize the values of the Accel sensor
	if (x > 405) x -= 1024;
	if (y > 405) y -= 1024;
	if (z > 405) z -= 1024;
	
	displayTextLine(1, "X: %4d", x);
	
	motor[B] = 50;
	motor[C] = 50;
	
	wait1Msec(2500);
	
	getValues();
	
	while(x < -60){
		getValues();
		motor[B] = 50;
		motor[C] = 50;
		 displayTextLine(1, "X: %4d", x);
		 displayTextLine(2, "Y: %4d", y);
		 displayTextLine(3, "Z: %4d", z);
		wait1Msec(10);
	}
	
	motor[B] = 0;
	motor[C] = 0;
	
	
	//while(true){
		// displayTextLine(1, "X: %4d", x);
		// displayTextLine(2, "Y: %4d", y);
		// displayTextLine(3, "Z: %4d", z);
	//}
}
