#pragma config(Sensor, S2,     ACCEL,          sensorI2CHiTechnicAccel)
#pragma config(Sensor, S3,     COMP,        sensorI2CHiTechnicCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

task main()
{
	int x=0, y=0, z=0, c=0;
	while (true) {
		getAccel(ACCEL, x, y, z);
		c = SensorValue[COMP];
		//Normalize the values
		if (x > 405) x -= 1024;
		if (y > 405) y -= 1024;
		if (z > 405) z -= 1024;

		displayTextLine(1, "X: %4d", x);
		displayTextLine(2, "Y: %4d", y);
		displayTextLine(3, "Z: %4d", z);
		displayTextLine(4, "C: %4d", c);
		wait1Msec(10);
	}
}
