#pragma config(Sensor, S2,     seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Globale variabele
float currHeading;
//De afwijking van de gyro sensor
int offset = 598;	

task getHeading () {
	float delTime = 0;
	float prevHeading = 0;
	float curRate = 0;

  while (true) {
  	//We starten een klok
    time1[T1] = 0;
    //De huidige snelheid van de hoek meten
    curRate = SensorValue[gyro] - offset;
    //Als de huidige snelheid groter is dan 3 graden / seconde
    if (abs(curRate) > 3) {
    	//De vorige hoek wordt de hudige hoek
      prevHeading = currHeading;
      //De nieuwe hoek wordt de vorige hoek + de snelheid (currate) * de tijd 
      currHeading = prevHeading + curRate * delTime;
      //Zorg dat de hoek tussen 0 en 360 gragen blijft
      if (currHeading > 360) currHeading -= 360;
      else if (currHeading < 0) currHeading += 360;
    }
    //Wachten 5 ms
    wait1Msec(5);
    //Bereken het verschil in tijd, ten opzichte van de vorige meting
    delTime = ((float)time1[T1]) / 1000;
  }
}

task main()
{
	//Start het meten van de hoek
	startTask(getHeading);

	wait1Msec(500);

	while (true) {
		//Twee gehele getallen 
		int location; // 1 - 9 (0 is geen meting)
		int rate; // De snelheid waarmee je draait (graden per seconde)
		
		location = SensorValue[seeker];
		rate = SensorValue[gyro] - offset;
		
		displayTextLine(1, "Seeker: %4d", location);
		displayTextLine(2, "Gyro:   %4d", rate);
		displayTextLine(3, "Heading: %f", currHeading);
		//Wait 10 ms
		wait1Msec(10);	
	}
}
